### ISSUE TITLE
Incorrect assignment operator used instead of equality operator

### ISSUE THREAD

**Issue by Shreehar-KE** [jamezmca/reactjs-full-course#3]
I found a very small bug in the code where the assignment operator (=) is used instead of the equality operator (==) in the array filter method of pokedex/src/components/PokeCard.jsx at `line 42`.
```js 
try {
  setLoadingSkill(true)
  const res = await fetch(moveUrl)
  const moveData = await res.json()
  console.log('Fetched move from API', moveData)
  const description = moveData?.flavor_text_entries.filter(val => {
    return val.version_group.name = 'firered-leafgreen'
  })[0]?.flavor_text
``` 
Expected Behaviour: This should return only the 'firered-leafgreen' description from the flavor_text_entries.

Actual Behaviour: The current implementation assigns a value instead of comparing which results in returning the description at index 0 from the flavor_text_entries.

**Comment by jamezmca** [comment]
Great catch! I have updated the code base to reflect the bug fix :D
